In [1]:
import numpy as np

In [2]:

uno = 2
dos = 4
tres = 6
u = 4
d = 5
t = 6
ud = 3
dd = 1
td = -2

r1 = 18
r2 = 24
r3 = 4

a = np.array([[uno,dos,tres],[u,d,t],[ud,dd,td]])
b = np.array([r1,r2,r3])
x=np.linalg.solve(a,b)
print("matriz")
print(a)
print("respuesta Respuesta general")
print(x)

q = ((uno*r1)+(dos*r2)+(tres*r3)) 
w = ((u*r1)+(d*r2)+(t*r3))
e = ((ud*r1)+(dd*r2)+(td*r3)) 
t = np.array([q,w,e])
print("Solucion particular")
print(t)


matriz
[[ 2  4  6]
 [ 4  5  6]
 [ 3  1 -2]]
respuesta Respuesta general
[ 4. -2.  3.]
Solucion particular
[156 216  70]
